DEFAULT_MODEL_FILE_LOCATION = 'model'
SOUND_MODEL_FILE_LOCATION = 'sound.model'
TEMPERATURE_MODEL_FILE_LOCATION = 'temperature.model'
SYNCED_AUDIO_FILE_LOCATION = 'orig.wav'
MFCC_FEATURE_FILE_LOCATION = 'orig.out'
FEATURE_NPY_FILE_LOCATION = 'orig.npy'
TEMPERATURE_NPY_FILE_LOCATION = 'temperature.npy'
TRAIN_BUFFER_FILE = 'train_buffer.txt'
TYPE_SOUND = 'sound'
TYPE_TEMP = 'temp'

PROBLEM_SEARCH_RANGE = 10
OUTLIER_TOLERANCE = 8
PROBLEM_TOLERANCE = 10

BOARD_SERVER_PORT = 80

DB_HOST = 'localhost'
DB_USER = 'root'
DB_PASSWD = 'proxima'
DB_NAME = 'proxima'
